# Generated by Django 3.0.7 on 2020-06-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views_tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='first_appearance',
            field=models.DateField(null=True),
        ),
    ]
